# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task -l
    silent: true


  write-git-info:
    desc: _
    silent: false
    vars:
      _suff: '{{._write_suff}}'
      _info: |-
        git_remote_url: $(echo $(git remote -v | head -n 1 | sed 's@origin@@g') | cut -d' ' -f1)
        git_current_branch: $(git rev-parse --abbrev-ref HEAD)
    cmds:
      - echo "{{._info}}" {{._suff}}

  write-version-info:
    desc: _
    silent: false
    vars:
      version_dir: '{{ default "." .version_dir}}'
      format: '{{ default "yaml" .format}}'
      _suff: '{{._write_suff}}'
      _info: |-
        version_prefix_txt: $(cat {{.version_dir}}/version_prefix.txt)
        project_name: $(cat {{.version_dir}}/project_name.txt)
    cmds:
      - echo "{{._info}}" {{._suff}}

  write-product-stamp:
    desc: _
    silent: true
    vars:
      _suff: '{{._write_suff}}'
      task_seq: |-
        write-version-info format=yaml \
        write-git-info
    env:
      _pretty: '{{._pretty}}'
    cmds:
      - echo '{{._suff}}'
      - |-
        task -s {{.task_seq}} {{._suff}}

  dump-conda-deps-lock:
    desc: dump conda packages state to
    cmds:
      - conda list -e > locks/deps.conda.dev-env.lock.list.txt
      - pip freeze > locks/deps.pip.dev-env.lock.list.txt
      - conda env export > locks/deps.conda-env-file.lock.list.yaml

