image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-python.python
    - littlefoxteam.vscode-python-test-adapter
    - hbenl.vscode-test-explorer
    - vscjava.vscode-java-test
    # - syntaf.vscode-python-test-adapter

tasks:
  - init: |
      python -m pip install -e . --no-deps
    command: |
      task ci-flow
