# https://taskfile.dev

version: '3'

tasks:
  default:
    silent: true
    cmds:
      - task: info
  
  # --- standard tasker extension tasks ----
  info:
    desc: show info
    cmds:
     - echo "main commands"

  list:
    desc: list all commands
    silent: true
    cmds:
      - task -l
  
  # --- standard tasker extension tasks ----

  test:
    desc: "Run all tests"
    cmds:
      - coverage run -m pytest -s  tests && coverage html

  build:
    desc: "Build results"
    cmds:
      - build-pypi-pack
      - build-pyinst-app
  
  build-pypi-pack:
    desc: "Build pypi package"
    cmds:
     - poetry build

  build-pyinst-app:
    desc: "Build pyinst app"
    cmds:
     - pyinstaller build
