# https://taskfile.dev

version: '3'

vars: &as_global_vars
  GREETING: Hello, World!
  const_venv: tasker-test-env
  conf_python_version: python=3.9

tasks:
  default:
    silent: true
    cmds:
      - task: info

  .:git-ignore-append-untracked:
    desc: appends untracked dirs to the end of .gitignore
    cmds:
      - git add .gitignore || true
      - git status -s | grep "??" | cut -d" " -f2 | tee -a .gitignore
      - git diff .gitignore | tee

  # --- standard tasker extension tasks ----
  _dump_vars:
    desc: dumps tasker vars
    silent: true
    env: *as_global_vars
    cmds:
      - |-
        export GRSH='"'
        yq read Taskfile.yml --tojson | jq -r '.vars | keys []' \
        | xargs -I@ bash -c 'echo @: "$GRSH$@$GRSH"'
  info:
    desc: main information about this dir api
    silent: true
    vars:
      main_task_list: >-
        info
        '"venv-resolve"'
        '"ci-flow"'
        '"run-test-gen-flowchart"'
    cmds:
      - echo '----------    META     --------------'
      - |-
        echo "\
        dirname: $(basename $(pwd))
        dirpath: $(pwd)
        filename: Taskfile.yml\
        "
      - echo '----------    VARS     --------------'
      - task: _dump_vars
      - echo '----------    TASKS     --------------'
      - |-
        for stage in {{.main_task_list}}; do
          _desc=$(yq read Taskfile.yml --tojson | jq -r .tasks."$stage".desc)
          printf "%-30s %-40s\n" "* $(echo $(echo $stage))" " * $_desc"
        done
      - echo '--------------------------------------'
      - echo 'for full tasklist please run "task -l"'


  # --- \standard tasker extension tasks ----

  venv-resolve:
    desc: 'resolve work/test venv={{.const_venv}}'
    vars:
      deps_conda_run_list_txt: "$(cat version/deps/deps.conda.run.list.txt | tr '\n' ' ')"
      deps_conda_test_list_txt: "$(cat version/deps/deps.conda.test.list.txt | tr '\n' ' ')"
    cmds:
      - |-
        conda list -n {{.const_venv}} 2>/dev/null \
        || conda create -n {{.const_venv}} {{.conf_python_version}} -y
        conda install -y -n {{.const_venv}} \
          {{.deps_conda_run_list_txt}} \
          {{.deps_conda_test_list_txt}}


  venv-active-show:
    desc: show command for venv activation
    silent: true
    cmds:
      - echo conda activate {{.const_venv}}

  with-venv:
    desc: run command within the venv
    cmds:
      - |-
        bash --login -c '
        conda activate {{.const_venv}}
        {{.cmd}}
        '

  verify-request:
    desc: check syntax, staling, etc
    cmds:
      - echo ok

  pre-build-test:
    desc: run tests without install (with PYTHONPATH)
    cmds:
      - echo tests:run-all-tests no_install=true

  ci-flow:
    desc: resolve deps, build product and test validate
    cmds:
      - task verify-request
      - task pre-build-test
      - task ci-build
      - task ci-test

  ci-build:
    desc: _
    cmds:
      - echo task build-pypi-pack
      - task: stam
      - echo task build-pyinst-pack

  stam:
    desc: _
    cmds:
      - echo one
      - task: pyfull

  test-them: test them

  ci-test:
    desc: _
    cmds:
      - echo task test

  pyfull:
    desc: _
    cmds:
    - |-
      python - << EOF | tee /tmp/tt.txt
      print("hello")
      EOF

  run-test-gen-flowchart:
    desc: print flowchart of provided taskfile
    cmds:
      - |-
        python3 tasker/tasker_ctl.py \
          --upath tests/data/sample-task/Taskfile.yml \
          resolve_static_task \
          ci-flow \
          jorney

