# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task -l
    silent: true

  cmder-shell:
    desc: enter to cmder shell
    cmds:
      - cmd /k C:\\Users\\user\\Apps\\cmder\\vendor\\bin\\vscode_init.cmd
    interactive: true

  
