
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the cicd.first branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: "${{ secrets.REPO_ACCESS_GITHUB_TOKEN }}"
          fetch-depth: 0
          
      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.13.5/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: 'version/deps/*.txt'
      - run: 'task pyenv-update-here'
      
      - run: 'task ci-flow'
