
name: ci-flow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: "${{ secrets.REPO_ACCESS_GITHUB_TOKEN }}"
          fetch-depth: 0
          
      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.13.5/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: 'version/deps/*.txt'

      - run: 'task pyenv-update-here'
        name: 'resolve-deps'
      
      - run: 'task ci-flow'
        name: 'ci-flow'
